config/routes.rb
Playground::Application.routes.draw do

  match 'user_urls/:id' => 'user_urls#index'

  get 'popular' => 'popular#index'

  resources :urls

  devise_for :users

  get ':short_url_key' => 'urls#short_url_redirect'

  root :to => 'urls#index'

end

app/models/url.rb
require "digest" # source - http://flawlessfuture.com/randomknowledge/?p=262

class Url < ActiveRecord::Base
  attr_accessible :short_url, :short_url_key, :url, :url_views, :user_id
  validates :url, :presence => true, :format => { :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
  
  belongs_to :user
  
  before_create :shorten_url

  def short_url
    "http://dangi.heroku.com/#{self.short_url_key}"
  end

  def self.increment_views(url)
    url.url_views += 1
    url.save
  end

  def self.find_popular(p = 1)
    self.paginate(:page => p, :per_page => 3).order("url_views DESC").all
  end

  def self.find_user_urls(u = 0)
    self.order("url_views DESC").find_all_by_user_id(u)
  end
  
  private
  
    def shorten_url
      begin
        self.short_url_key = Digest::MD5.hexdigest(rand(10000).to_s)[0, 5]
        existing = Url.find_by_short_url_key(self.short_url_key)
      end while ! existing.nil?
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :urls

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/popular_controller.rb
class PopularController < ApplicationController
  def index
    @urls = Url.find_popular(params[:page])
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url = Url.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/new
  # GET /urls/new.json
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/1/edit
  def edit
    @url = Url.find(params[:id])
  end

  # POST /urls
  # POST /urls.json
  def create
  
    @url = Url.create(params[:url])
    
    respond_to do |format|
      if @url.save
        if signed_in?
          @url.user_id = current_user.id 
          @url.save
        end
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
      else
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /urls/1
  # PUT /urls/1.json
  def update
    @url = Url.find(params[:id])

    respond_to do |format|
      if @url.update_attributes(params[:url])
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url = Url.find(params[:id])
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end
  
  def short_url_redirect
    @url = Url.find_by_short_url_key(params[:short_url_key])
    Url.increment_views(@url)
    redirect_to(@url.url)
  end

end

app/controllers/user_urls_controller.rb
class UserUrlsController < ApplicationController
  
  before_filter :current_user_authenticate 

  def current_user_authenticate
    flash[:error] = "You do not have access to view this page."
    redirect_to(user_session_path) unless user_signed_in? && current_user.id == params[:id].to_i
  end

  def index
    @urls = Url.find_user_urls(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/user_urls_helper.rb
module UserUrlsHelper
end

app/views/layouts/_navigation.html.erb
<%= link_to "Dangi", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Playground" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <%= render 'layouts/navigation' %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
				<%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Popular", "/popular"  %></li>
					<% if user_signed_in? %>
					  <li><%= link_to "My URLs", "/user_urls/#{current_user.id}" %></li>
					<% end %>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/popular/index.html.erb
<h1>Popular URLs</h1>
<p></p>

  <table>
  <tr>
    <td>Url</td>
    <td>Views</td>
  <tr>
  <% @urls.each do |url| %>
    <tr>
      <td><%= url.url %></td>
      <td><%= url.url_views %></td>
    </tr>
  <% end %>
  </table>

<%= will_paginate @urls %>

app/views/urls/_form.html.erb
<%= form_for @url, :html => { :class => 'form-horizontal' } do |f| %>
  <p>Please enter the URL you'd like to shorten below.</p>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                urls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<%- model_class = @url.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/urls/index.html.erb
<%- model_class = Url.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:short_url) %></th>
      <th><%= model_class.human_attribute_name(:url_views) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:short_url_key) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= link_to url.id, url_path(url) %></td>
        <td><%= url.url %></td>
        <td><%= url.short_url %></td>
        <td><%= url.url_views %></td>
        <td><%= url.user_id %></td>
        <td><%= url.short_url_key %></td>
        <td><%=l url.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_url_path(url), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      url_path(url),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_url_path,
            :class => 'btn btn-primary' %>

app/views/urls/new.html.erb
<%- model_class = @url.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/urls/show.html.erb
<%- model_class = @url.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @url.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_url) %>:</strong></dt>
  <dd><%= @url.short_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url_views) %>:</strong></dt>
  <dd><%= @url.url_views %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @url.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_url_key) %>:</strong></dt>
  <dd><%= @url.short_url_key %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              urls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_url_path(@url), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              url_path(@url),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/user_urls/index.html.erb
<h1>User <%= params[:id] %> URLs</h1>

  <table>
  <tr>
    <td>Url</td>
    <td>Views</td>
  <tr>
  <% @urls.each do |url| %>
    <tr>
      <td><%= url.url %></td>
      <td><%= url.url_views %></td>
    </tr>
  <% end %>
  </table>